@Library('olcne-pipeline') _
import com.oracle.olcne.pipeline.BranchPattern

String version  = "0.40.1"
String imageTag = "v" + version

imagePipeline(
        branchPattern: new BranchPattern(master: 'oracle/release/' + version, feature: '(?!^release/.*$)(^.*$)'),
        containers: [('container-registry.oracle.com/olcne/thanos:' + imageTag): 'olcne/thanos:' + imageTag],
        platforms: [ 'ol9'],
        architectures: ['x86_64', 'aarch64'],
        buildScript: "bash olm/build-image.sh ${version}"
)
