@Library('olcne-pipeline') _
import com.oracle.olcne.pipeline.BranchPattern

String version = "{{{ .major }}}.{{{ .minor }}}.{{{ .patch }}}"

imagePipeline(
  branchPattern: new BranchPattern(master: 'oracle/release/' + version, feature: '(?!^release/.*$)(^.*$)'),
  containers: [('container-registry.oracle.com/olcne/thanos:v' + version): 'olcne/thanos:v' + version],
  buildScript: "sh olm/build-image.sh",
  publishImage: true,
)
